version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: restaurant
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  backend:
    build: ./backend_Golang
    container_name: golang-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: restaurant

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
